language: node_js
node_js:
  - '5.1'
addons:
  apt:
    packages:
      - wine
script:
  - npm --depth Infinity update
  - npm run test-ci
before_deploy:
  - npm run zip-binaries
deploy:
  provider: releases
  api_key:
    secure: fnzRn6GAv7ppX2HhmiJ8Z0Ej0p7M2NlJ0ondxgDY1qu6Ukc9zT6A7Qr4vwnSkYihjkjfyDQRN8Fz09/pJRHfk5ydnptAvJoV3sErb2DQ62NVEkDXybEiKC9+zBuXGTaBOSOl4WfYrfaUe3KdU2gjt+4mIAy5dnWWm93sqZbd5gK7V6zjksZo8ca8/qBL4OaUMYLgB5Uy3yJvm8Kx7Y5gBYTFpKuDWSr6wQRcQ7JAFNUoRbyWXeCyrV32KULsiImrTLGBp2tIBb6R5LN5kWrfuSAdFOvaEq/ToUiTykoTCpm6FMUvbhG697rNe4AebW3fUazcXB3S9GBUdnUNJYXIVULxDfQ4z+ZDpH9iu+X9QDEM4dvvHGJAxOJyQOEoOQWqEVebxLWhYY2TuJjdQstYvUA4xga9iJ+T0+rjRP+2ngMluhrXzXsmKDAbdJTajm74TvRKh/w5sIzjb8n+Pup0Dp+awZLE5ZkCEsPeTN66HesvMur2sLS0gFPdvjEsR/8tWVqPVBH5fVDKVdbnbv1WzN/eHExOx6qIV3GiMcDmK14CQ100VRTlqommpxM+S/LwL7F6vgwg9oi1OONBJpfOWRSJCD6huFPSA3tbS2eh3FkyAkcxGSbOFNSC3e2F07Pmjb0dGaKWBQ9D025xe1/I0qX8vx7TL49SjiEVznKGNhY=
  file:
  - binaries/James-darwin-x64.zip
  - binaries/James-linux-ia32.zip
  - binaries/James-linux-x64.zip
  - binaries/James-win32-ia32.zip
  - binaries/James-win32-x64.zip
  skip_cleanup: true
  on:
    tags: true
cache:
  apt: true
  directories:
    - node_modules
    - $HOME/.electron