version: '{build}'

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - npm prune
  - npm install

build_script:
  - npm run test-ci
  - npm run dist:win64

environment:
  GH_TOKEN:
      secure: HnT2ViVK97gtyZrlPH1C9zM/m3YErp8kY9FtO7wUhcoLG8TZiR1oLiBx+27eCWrX

test: off